dist: trusty
language: python
git:
  depth: 1
cache:
  apt: true
python:
- '3.6'
install:
- pip install pytest coveralls
- python setup.py install
script:
- coverage run --source=pyMathBitPrecise setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: nic30
  password:
    secure: NuAvdl0z52tlCk2/fI/gDyEdyfCZr2YY2/58Zc8PzLg4Qd4eRRrHg7hXeXC23j8UYDD0dO3rtfVCbazsyN340aNkQhHiX2eSl/Kz7at7lD1f1ggtvnI1cTh4WpbN9NY4lvikwbMgPd4p4Py8XtRrRwR+nlQYgNmIwlvxKM3FCYMYHY2/IopETsogDx0Yz6ZBs1oTdap6nbDci1G3RAthjMkSwuxx5ERjCHFnZanbRpn23xn67wBnSRPFCe2kc6AJ/gxz8nTyV3a2l9b2w8RLp+BtnTptIHKlPQHWSek4zLziQbPCEjM7Sd624ai87LB4SaIeeIGaNfMHXDStdBlkFT4GpORc8Hltwxz8T2dD9j1Z8jifl0SpV1nTwVHdWglzN6t4cCo2YPlJ5JLDcPnalWeqPmOWB6erpFV4WE8TCHmdQ9fR6fPvL3OGIgLp/46JbzG37RXtDWDdZr42BZ/XjxT0NA9DE3VS6gNouiSMza943Xts//h1MlC9+hfoW6tEaHnu7Lf4uHKviu3NjC4bvClzeiPLPIZ12MFiwKXEA11SXnNpknllkSisgLJ2SverdLvml+y2b8tHeXB9YwKFCqGZ4wfiOox3ec7MnLNUh0Prl5sp5Hrj5VRaMJmwHsXz8hmY1ztpErCVZL+KTRv4qCmqiyMRHB0kXRePzBCN9zk=
  on:
    tags: true
    branch: master
