dist: trusty
language: python
git:
  depth: 1

cache:
  apt: true

python:
  - '3.6'
#  - "nightly"

install:
  - pip install pytest coveralls
  - python setup.py install

script:
  - coverage run --source=pyMathBitPrecise setup.py test

#deploy:
#  provider: pypi
#  user: nic30
#  password:
#    secure:
#  on:
#    tags: true
#    branch: master

after_success:
- coveralls
