dist: trusty
language: python
git:
  depth: 1
cache:
  apt: true
python:
- '3.6'
install:
- pip install pytest coveralls
- python setup.py install
script:
- coverage run --source=pyMathBitPrecise setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: nic30
  password:
    secure: AEQcTgnhlegP+P+CX4wcUHU772MTQDtihAsrViB0o6qe7D44qfSE3SG35IHCXKlrZnckyAXAXuMneTlocqZ2vpyJiTonCwHIvd9b8O40zk0XbRDJoobJNnguWvm9Q9HUAepLyT/qxpDuhcc7tkBsZTMnV8Nm3H35kUhXnzqZMbc15iZR/7a5bmEA8cLspKoc4XWPo5AqpGdj3ss8Qs8irWlMsxsoJRhkczCXplpR3Kjv7Zj+eYUQGP6zeUfrXgAS5ZcQon9mEnn9EJn1frJBo6blI3saOGs6cAjo8wsWBSsTfIFZFBitPW7PxfSmeSNzZHDS2gqTgeone8JGeB3cZtfvaD59GhgUTAO3M9Qy6MwoSdCiihbno2QuukvZRiGSw3dN7IqO3TWCwC7QuSQg1g14qAcyVHyw+7kTndedhLiwJMznpNMb+Nyl25dCJAGUv3AT9KMF/ZtuvnDWMV3YKnxCe1XMBx8LYJSabeWn3anzRg8rxF7wKQIH0ipyYkMn5sjBoYjSl4S/EgPHFNUkhRGd4KhJZhDUdgQWDhTTMroxYL+OQU2lKHxfEI0A+9BWuVO0lVFVSk9KCEx13W/cB6ksrlwJcM1UAmA8J/iP0gHZ0URDdBTG/Aq0Aga0rd3XDY2RhHvLBI0KqYXKfcztGsss+oXf0ODtlwgarMX3zXM=
  on:
    tags: true
    branch: master
