dist: trusty
language: python
git:
  depth: 1
cache:
  apt: true
python:
- '3.7'
install:
- pip install pytest coveralls
- python setup.py install
script:
- coverage run --source=pyMathBitPrecise setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: nic30
  password:
    secure: C3NFB15+JOUZzhzwTRW5GHJa8eKiMvvFrb1iLn7Llm7tiiwR3oTDGftusd/C4fX10BMKqozQBn3WVnGDFhcLLGEaJnwgtVY8pPdsgsO5iTKj7bgXJ8cOHIn6Rvtz2G6CXDl3haa88mBj4apAgpApoR5tmopnT6EqR6hhsv/9qI6yM55oaeKeGNhidNiTDZSo36Ol7rN36R2Zz1q0cPvw71dZczRoo10qacqjXQUydTDvu9djVdXNsKCun0w/UtuNmso2I2i2JOuwHf/MJhjkmJE7Yp9T5sUElu+cUibIpSduyb3jGY+Yf9mbWN5ojL4gXqLgeLBm/ZKLOFtrlJTuE8J/NuLYX4HFEfeBv9Ym1VdfpPMRWjYtov9ARTv37sAKnc7tnm+51mS/tGdISr3BWg5+l1gXIi+3k49g47qePhJEuZje0FdGspH4L7a7taP+QVr7tjqd15l1cOognwtPukwD62AgCFQLs8VSJ/SO7wUQHjbUQfHJCdVvtyUJpje2PSqL/SeVUXAZJg4raIFNCjZ5Al5lg0lGZeygvj+mT3SNHMD9D8mMRC4ofzRXqJYilPvtDXr+rtPKk0zovYtHHVtP5g2wgRVpdMo+qUrSwe3EavabI904l/96+ifgBkIb7Dx+Y9zXMbNLKWLwDOlwAu00jSdQthtFBB5Zwu/GL+4=
  on:
    tags: true
    branch: master
