dist: trusty
language: python
git:
  depth: 1
cache:
  apt: true
python:
- '3.6'
install:
- pip install pytest coveralls
- python setup.py install
script:
- coverage run --source=pyMathBitPrecise setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: nic30
  password:
    secure: frmfZKt4MLrYxROFy03nhQMr2KcWUvTXFniU86laoo/AHbKfOFyhEApiJWQGn4LkK1tzAhGHBr13pjk2+uIxhL3OzR12RbkG24udwSQLQbnLhAcYfq1lf65XvCTLr8RNSiIlvl1jRJOQODVrOKvdwsDtQiVvLensWYKfiYWHQwvJBm7iaOlZfN06CJSQJw8SHYex0q3/VB5N4Nbnb/TpU9e+ozauibwP28K+3JpFAr67FxxH/cwCkUOS5uKscj9B/3EWXT2vWNs+w/U50ZFaX4WjteLjhGEHZxAJHMrTxsfMlv7h7nQXGCSemVAsPoBlYiuzfcYO6iIs5zCNhzMYLlIbnm+QfdmYZbXvAhRm4YhrPcThDvX55BeuoHcltMjmIss1h8b9KzALYqsN0IX9kahrd6PysTKyd2cIJbH+Kj7d65VhrWYKc0OCu0WuiHaFYeeEaXbpXlqhsVT0+EX7zKyj5sjLcpLf0UBnGHb5wCLm7LiCkvsixkuFbjznqcIBQkNyZ6VGGZTSNx3t1HvCp6U+ABpo3VmBMafsZioAsNiKBhlGll2gFtRbMVUZBEKYtgZjcoklMVUN0mQwUgwZoTLKsmyc+H2bhcka0R9DpTY/53HkGAZLRzqhK2TTPRmgI/0NSavEj8W2OsBvgf7+qGAaYKSO7DbuHi3pAldrphg=
  on:
    tags: true
    branch: master
