dist: trusty
language: python
git:
  depth: 1
cache:
  apt: true
python:
- '3.6'
install:
- pip install pytest coveralls
- python setup.py install
script:
- coverage run --source=pyMathBitPrecise setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: nic30
  password:
    secure: O75120o96OSLCBJvJOZvg/VWTWyF1BIcz0oPi82pBIFdORo013LQSxBfm9l+3kaq8feSZR79Hgr2MoGWvn1gHBgIhKJv8zbNHB06GTFKg0heCxsMuvEFXkLIOgcu60ycU2XjP5Igmwccu8p3mCuPIe5YuTkYs4B33OBXAL7D+Azlkm29rP340uUTd/4Q3aPSnfrtimYIjClmJtEk9RHEbyLo7E5A4kon3ih2sXmbtcFfv/Z2M3c0aU5RnHQAburMc51NCPhAK+m0ElLL/rvioQWvEWMXI84P1WSg/V1UVKo3Vr+82o/Ae0zd+Fpgu5Hd2y7DRwSJbMjp48zenRASBZxiIuG2Vty7HPxdjQyMQA8oT3y1sIRTOj5rdQcWFzip1LRcoTcoePk1iAScqhyptqrNkCxBjdVZloFeeQABLjaicICTY5bNpivIE10AmjV00mfZqiSphRUYb3e/Vc62k9NwT4GY4oW/WOPevxnOQbd4xJHZKD0q1uyuweudbCjCRiS+8py9siri3sxNfj5IXO54vkGSqrgegAfXWJrlWdstXcOAe6GI0vJfcJ89p5KoVdTeN9r/eh8qPC3baZDV5qGAhrDnYcin+VS+Im2ZFUuCMtnisDTf1TN9rE1j5hlGtgurQSOq8+10h8hMrAydGeqlM5kcrIl55wCaK1VXy4U=
  on:
    tags: true
    branch: master
